---
name: 'Terraform'
on:
  pull_request:
  push:
    branches:
      - main
env:
  terraform_version: 1.3.5

jobs:
  linters:
    name: 'Terraform linters'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout the codebase'
        uses: actions/checkout@v3

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: 'Run terraform fmt'
        continue-on-error: true
        run: terraform fmt -check -recursive -diff

      - name: 'Setup tflint'
        uses: terraform-linters/setup-tflint@v3

      - name: 'Run tflint'
        continue-on-error: true
        run: |
          tflint --init
          tflint -f compact --recursive
